sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
    - pip install flake8 mock pytest pytest-cov coveralls
    - pip install sphinx sphinx_rtd_theme
    - pip install .
script:
    - python -m flake8
    - python -m sphinx -b doctest docs docs/_build
    - python -m sphinx -b html -W docs docs/_build
    - py.test -s -v --cov=binarytree
after_success:
    - coveralls
